apiVersion: 1

datasources:
  - name: InfluxDB-NetworkOptimizer
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: network-optimizer
      defaultBucket: network_optimizer
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true
